name: KitsuneChat
version: 2.0.0-SNAPSHOT
main: net.cyberkitsune.prefixchat.KitsuneChat
api-version: "1.15"
authors: [CyberKitsune, Alynna, Snooper]
softdepend: [Vault, Multiverse-Core]
commands:
     kc:
      description: KitsuneChat commands.
     me:
      description: Perform an action in text.
     msg:
      description: Send a private message.
     r:
      description: Reply to a message in chat.
     nick:
      description: Change your nickname.
      
permissions:
     kitsunechat.adminchat:
        description: Allows use of adminchat
        default: op
     kitsunechat.staffchat:
        description: Allows the use of staff chat.
        default: op
     kitsunechat.no.*:
        description: Deny ALL the chat!
        default: false
        children:
           kitsunechat.no.global: true
           kitsunechat.no.world: true
           kitsunechat.no.party: true
     kitsunechat.no.global:
        description: Denies use of using /kc to default to global chat.
        default: false
     kitsunechat.no.world:
        description: Denies use of using /kc to default to world chat.
        default: false
     kitsunechat.no.party:
        description: Denies use of using /kc to default to party chat.
        default: false
     kitsunechat.ignoreradius:
        description: Allows the user to hear ALL local chat.
        default: false
     kitsunechat.nick:
        description: Allows you to change your nickname.
        default: false
     